const styles = {
  container: {
    backgroundColor: '#2B2633',
    minHeight: '100vh',
    color: 'white',
    padding: '20pt 40pt',
    boxSizing: 'border-box',
  },
  title: {
    fontSize: '18pt',
    marginBottom: '20pt',
  },
  button: {
    padding: '12px 24px',
    backgroundColor: '#E7E964',
    color: '#2B2633',
    borderRadius: '8px',
    fontSize: '14pt',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 700,
    boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.1)',
    '&:hover': {
      backgroundColor: '#D4D455',
    },
  },
  modalBox: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '520px',
    backgroundColor: '#3C3A45',
    color: 'white',
    boxShadow: '0px 10px 20px rgba(0, 0, 0, 0.2)',
    borderRadius: '16px',
    padding: '30px 30px',
    boxSizing: 'border-box',
    overflowY: 'auto',
    transition: 'all 0.3s ease',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '90vh',
  },
  modalBoxMedium: {
    width: '60vw',
    height: '70vh',
    borderRadius: '16px',
    padding: '20px',
  },
  modalBoxLarge: {
    width: '85vw',
    height: '85vh',
    borderRadius: '16px',
    padding: '20px',
  },
  titleBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginBottom: '10px',
  },
  modalTitle: {
    fontSize: '14pt',
    fontWeight: 600,
    color: 'white',
    textAlign: 'center',
  },
  closeButton: {
    position: 'absolute',
    right: '8px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#E57373',
    backgroundColor: 'transparent',
    borderRadius: '50%',
    padding: '2px',
    fontSize: '16px',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#E57373',
      color: 'white',
    },
  },
  inputLabel: {
    color: 'white',
    marginBottom: '10px',
    fontSize: '14px',
    fontWeight: 500,
  },
  textField: {
    marginBottom: '20px',
    '& input': { color: 'white' },
    '& label': { color: 'white' },
    '& .MuiInputLabel-root.Mui-focused': { color: '#E7E964' },
    '& .MuiOutlinedInput-root': {
      '& fieldset': { borderColor: 'white' },
      '&:hover fieldset': { borderColor: '#E7E964' },
      '&.Mui-focused fieldset': { borderColor: '#E7E964' },
    },
  },
  fileInputContainer: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '20px',
  },
  fileInputButton: {
    backgroundColor: '#88868B',
    color: '#2B2633',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    '&:hover': {
      backgroundColor: '#E7E964',
      color: '#2B2633',
    },
  },
  fileName: {
    fontSize: '14px',
    color: 'white',
    marginLeft: '10px',
  },
  canvasContainer: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    backgroundColor: '#2B2633',
    borderRadius: '12px',
    overflow: 'hidden',
    padding: '10px',
  },
  canvas: {
    width: '100%',
    maxWidth: '600px',
    height: '100%',
    maxHeight: '400px',
    backgroundColor: '#3C3A45',
    borderRadius: '8px',
  },
  previewArea: {
    flex: 3,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2B2633',
    borderRadius: '12px',
    overflow: 'hidden',
    padding: '10px',
  },
  previewCanvas: {
    width: '100%',
    height: '100%',
    backgroundColor: '#3C3A45',
  },
  toolsContainer: {
    flex: 1,
    backgroundColor: '#3C3A45',
    borderRadius: '12px',
    padding: '20px',
    color: 'white',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginLeft: '20px',
  },
  toolButton: {
    backgroundColor: '#555',
    color: 'white',
    borderRadius: '8px',
    padding: '10px 20px',
    margin: '10px 0',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#777',
    },
  },
  sliderContainer: {
    position: 'absolute',
    bottom: '20px',
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 2,
    width: '280px',
    padding: '6px 24px',
    backgroundColor: 'rgba(50, 50, 60, 0.5)',
    backdropFilter: 'blur(10px)',
    borderRadius: '12px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    boxShadow: '0px 0px 5px rgba(0,0,0,0.5)',
  },
  sliderLabel: {
    color: 'white',
    marginBottom: '5px',
    fontSize: '12px',
  },
  slider: {
    width: '100%',
    color: '#E7E964',
    '& .MuiSlider-thumb': {
      width: '16px',
      height: '16px',
      '&:focus, &:hover, &.Mui-active': {
        boxShadow: '0px 0px 0px 10px rgba(231, 233, 100, 0.3)',
      },
    },
    '& .MuiSlider-rail': {
      opacity: 0.5,
      backgroundColor: '#88868B',
    },
    '& .MuiSlider-track': {
      backgroundColor: '#E7E964',
    },
  },
  stepper: {
    width: '100px',
    padding: 0,
    '& .MuiStep-root': {
      padding: 0,
    },
    '& .MuiStepIcon-root': {
      color: '#4D4B50',
      fontSize: '24px',
      '&.Mui-active': {
        color: '#E7E964',
      },
      '&.Mui-completed': {
        color: '#E7E964',
      },
    },
    '& .MuiStepConnector-root': {
      display: 'none',
    },
    '& .MuiStepLabel-label': {
      display: 'none',
    },
  },
  controlButtons: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '20px',
  },
  backButton: {
    backgroundColor: '#4D4B50',
    color: 'white',
    borderRadius: '8px',
    padding: '8px 24px',
    fontWeight: 600,
    fontSize: '14px',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#5E5C62',
    },
  },
  nextButton: {
    backgroundColor: '#E7E964',
    borderRadius: '8px',
    padding: '8px 24px',
    fontWeight: 600,
    fontSize: '14px',
    color: '#2B2633',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#D4D455',
    },
  },
  modalBoxLarge: {
    width: '85vw',
    height: '85vh',
    borderRadius: '8px',
    padding: '20px',
    backgroundColor: '#3C3A45',
},
canvas: {
    width: '100%',
    height: '100%',
    borderRadius: '8px',
    display: 'block',
    boxShadow: 'inset 0px 0px 10px rgba(0, 0, 0, 0.5)',
},
};

export default styles;
